Change CI setting

diff --git a/.github/workflows/ros2_ci.yml b/.github/workflows/ros2_ci.yml
--- a/.github/workflows/ros2_ci.yml
+++ b/.github/workflows/ros2_ci.yml
@@ -1,4 +1,4 @@
-name: Build and Test
+name: Build
 
 on:
   push:
@@ -12,7 +12,7 @@ on:
 #     types: [published]
 
 jobs:
-  build_and_test:
+  build:
     strategy:
       matrix:
         os:
@@ -67,20 +67,20 @@ jobs:
         if: steps.build_test.outcome == 'failure'
         run: echo "result - failure" && exit 1
 
-      - name: Run tests
-        id: run_test
-        run: |
-          cd ros2_ws &&
-          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
-          . install/setup.sh &&
-          colcon test && 
-          colcon test-result
-        continue-on-error: true
+      # - name: Run tests
+      #   id: run_test
+      #   run: |
+      #     cd ros2_ws &&
+      #     . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+      #     . install/setup.sh &&
+      #     colcon test &&
+      #     colcon test-result
+      #   continue-on-error: true
 
-      - name: run_test command success
-        if: steps.run_test.outcome == 'success'
-        run: echo "result - success"
+      # - name: run_test command success
+      #   if: steps.run_test.outcome == 'success'
+      #   run: echo "result - success"
 
-      - name: run_test command failure
-        if: steps.run_test.outcome == 'failure'
-        run: echo "result - failure" && exit 1
+      # - name: run_test command failure
+      #   if: steps.run_test.outcome == 'failure'
+      #   run: echo "result - failure" && exit 1
